// flow-typed signature: 3afc5cd2d05021aa23058eef1b3afaf0
// flow-typed version: <<STUB>>/mobx-utils_v^3.2.1/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mobx-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mobx-utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mobx-utils/lib/async-action' {
  declare module.exports: any;
}

declare module 'mobx-utils/lib/chunk-processor' {
  declare module.exports: any;
}

declare module 'mobx-utils/lib/create-view-model' {
  declare module.exports: any;
}

declare module 'mobx-utils/lib/from-promise' {
  declare module.exports: any;
}

declare module 'mobx-utils/lib/from-resource' {
  declare module.exports: any;
}

declare module 'mobx-utils/lib/guarded-when' {
  declare module.exports: any;
}

declare module 'mobx-utils/lib/keep-alive' {
  declare module.exports: any;
}

declare module 'mobx-utils/lib/lazy-observable' {
  declare module.exports: any;
}

declare module 'mobx-utils/lib/mobx-utils' {
  declare module.exports: any;
}

declare module 'mobx-utils/lib/now' {
  declare module.exports: any;
}

declare module 'mobx-utils/lib/observable-stream' {
  declare module.exports: any;
}

declare module 'mobx-utils/lib/queue-processor' {
  declare module.exports: any;
}

declare module 'mobx-utils/lib/src/chunk-processor' {
  declare module.exports: any;
}

declare module 'mobx-utils/lib/src/create-view-model' {
  declare module.exports: any;
}

declare module 'mobx-utils/lib/src/from-promise' {
  declare module.exports: any;
}

declare module 'mobx-utils/lib/src/from-resource' {
  declare module.exports: any;
}

declare module 'mobx-utils/lib/src/guarded-when' {
  declare module.exports: any;
}

declare module 'mobx-utils/lib/src/keep-alive' {
  declare module.exports: any;
}

declare module 'mobx-utils/lib/src/lazy-observable' {
  declare module.exports: any;
}

declare module 'mobx-utils/lib/src/mobx-utils' {
  declare module.exports: any;
}

declare module 'mobx-utils/lib/src/now' {
  declare module.exports: any;
}

declare module 'mobx-utils/lib/src/observable-stream' {
  declare module.exports: any;
}

declare module 'mobx-utils/lib/src/queue-processor' {
  declare module.exports: any;
}

declare module 'mobx-utils/lib/src/utils' {
  declare module.exports: any;
}

declare module 'mobx-utils/lib/subscribing-observable' {
  declare module.exports: any;
}

declare module 'mobx-utils/lib/test/type-tests' {
  declare module.exports: any;
}

declare module 'mobx-utils/lib/utils' {
  declare module.exports: any;
}

declare module 'mobx-utils/lib/when-async' {
  declare module.exports: any;
}

declare module 'mobx-utils/mobx-utils.module' {
  declare module.exports: any;
}

declare module 'mobx-utils/mobx-utils.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mobx-utils/lib/async-action.js' {
  declare module.exports: $Exports<'mobx-utils/lib/async-action'>;
}
declare module 'mobx-utils/lib/chunk-processor.js' {
  declare module.exports: $Exports<'mobx-utils/lib/chunk-processor'>;
}
declare module 'mobx-utils/lib/create-view-model.js' {
  declare module.exports: $Exports<'mobx-utils/lib/create-view-model'>;
}
declare module 'mobx-utils/lib/from-promise.js' {
  declare module.exports: $Exports<'mobx-utils/lib/from-promise'>;
}
declare module 'mobx-utils/lib/from-resource.js' {
  declare module.exports: $Exports<'mobx-utils/lib/from-resource'>;
}
declare module 'mobx-utils/lib/guarded-when.js' {
  declare module.exports: $Exports<'mobx-utils/lib/guarded-when'>;
}
declare module 'mobx-utils/lib/keep-alive.js' {
  declare module.exports: $Exports<'mobx-utils/lib/keep-alive'>;
}
declare module 'mobx-utils/lib/lazy-observable.js' {
  declare module.exports: $Exports<'mobx-utils/lib/lazy-observable'>;
}
declare module 'mobx-utils/lib/mobx-utils.js' {
  declare module.exports: $Exports<'mobx-utils/lib/mobx-utils'>;
}
declare module 'mobx-utils/lib/now.js' {
  declare module.exports: $Exports<'mobx-utils/lib/now'>;
}
declare module 'mobx-utils/lib/observable-stream.js' {
  declare module.exports: $Exports<'mobx-utils/lib/observable-stream'>;
}
declare module 'mobx-utils/lib/queue-processor.js' {
  declare module.exports: $Exports<'mobx-utils/lib/queue-processor'>;
}
declare module 'mobx-utils/lib/src/chunk-processor.js' {
  declare module.exports: $Exports<'mobx-utils/lib/src/chunk-processor'>;
}
declare module 'mobx-utils/lib/src/create-view-model.js' {
  declare module.exports: $Exports<'mobx-utils/lib/src/create-view-model'>;
}
declare module 'mobx-utils/lib/src/from-promise.js' {
  declare module.exports: $Exports<'mobx-utils/lib/src/from-promise'>;
}
declare module 'mobx-utils/lib/src/from-resource.js' {
  declare module.exports: $Exports<'mobx-utils/lib/src/from-resource'>;
}
declare module 'mobx-utils/lib/src/guarded-when.js' {
  declare module.exports: $Exports<'mobx-utils/lib/src/guarded-when'>;
}
declare module 'mobx-utils/lib/src/keep-alive.js' {
  declare module.exports: $Exports<'mobx-utils/lib/src/keep-alive'>;
}
declare module 'mobx-utils/lib/src/lazy-observable.js' {
  declare module.exports: $Exports<'mobx-utils/lib/src/lazy-observable'>;
}
declare module 'mobx-utils/lib/src/mobx-utils.js' {
  declare module.exports: $Exports<'mobx-utils/lib/src/mobx-utils'>;
}
declare module 'mobx-utils/lib/src/now.js' {
  declare module.exports: $Exports<'mobx-utils/lib/src/now'>;
}
declare module 'mobx-utils/lib/src/observable-stream.js' {
  declare module.exports: $Exports<'mobx-utils/lib/src/observable-stream'>;
}
declare module 'mobx-utils/lib/src/queue-processor.js' {
  declare module.exports: $Exports<'mobx-utils/lib/src/queue-processor'>;
}
declare module 'mobx-utils/lib/src/utils.js' {
  declare module.exports: $Exports<'mobx-utils/lib/src/utils'>;
}
declare module 'mobx-utils/lib/subscribing-observable.js' {
  declare module.exports: $Exports<'mobx-utils/lib/subscribing-observable'>;
}
declare module 'mobx-utils/lib/test/type-tests.js' {
  declare module.exports: $Exports<'mobx-utils/lib/test/type-tests'>;
}
declare module 'mobx-utils/lib/utils.js' {
  declare module.exports: $Exports<'mobx-utils/lib/utils'>;
}
declare module 'mobx-utils/lib/when-async.js' {
  declare module.exports: $Exports<'mobx-utils/lib/when-async'>;
}
declare module 'mobx-utils/mobx-utils.module.js' {
  declare module.exports: $Exports<'mobx-utils/mobx-utils.module'>;
}
declare module 'mobx-utils/mobx-utils.umd.js' {
  declare module.exports: $Exports<'mobx-utils/mobx-utils.umd'>;
}
