// flow-typed signature: 2b25e220e39baeeba35cea9ee50a5151
// flow-typed version: <<STUB>>/react-native-datepicker_v^1.6.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-datepicker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-datepicker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-datepicker/style' {
  declare module.exports: any;
}

declare module 'react-native-datepicker/test/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-datepicker/index' {
  declare module.exports: $Exports<'react-native-datepicker'>;
}
declare module 'react-native-datepicker/index.js' {
  declare module.exports: $Exports<'react-native-datepicker'>;
}
declare module 'react-native-datepicker/style.js' {
  declare module.exports: $Exports<'react-native-datepicker/style'>;
}
declare module 'react-native-datepicker/test/index.test.js' {
  declare module.exports: $Exports<'react-native-datepicker/test/index.test'>;
}
