import flags from './flags';

export default {
  silicondzor: 'Silicondzor',
  tech_events: 'Tech Events',
  jobs_board: 'Jobs board',
  discussion: 'Discussions',
  emoji_flag: flags.en,
  name: 'English',
  settings: 'Settings',
  push_notification: 'Push Notifications',
  language: 'Language',
  up: 'up',
  down: 'down',
  search: 'Search...',
  be_kind_in_what_you_say: 'Be kind and respectful in what you say',
  new_post_title: 'New Discussion',
  new_tech_event_title: 'New Tech Event',
  new_tech_bug_bounty: 'New bug bounty',
  new_tech_job_posting: 'New Job Posting',
  bug_bounty: 'Bug Bounty',
  jobs_board: 'Jobs',
  screens: {
    tech_discussions: 'Discussions',
    tech_events: 'Upcoming events',
    bug_bounty_board: 'Bug Bounties',
    jobs_board: 'Jobs',
    settings: 'Settings',
  },
};
