import flags from './flags';

export default {
  en: {
    silicondzor: 'Silicondzor',
    tech_events: 'Tech Events',
    jobs_board: 'Jobs board',
    discussion: 'Discussions',
    emoji_flag: flags.en,
    name: 'English',
    settings: 'Settings',
    push_notification: 'Push Notifications',
    language: 'Language',
    up: 'up',
    down: 'down',
    search: 'Search...',
    be_kind_in_what_you_say: 'Be kind and respectful in what you say',
    new_post_title: 'New Discussion',
    new_tech_event_title: 'New Tech Event',
    new_tech_bug_bounty: 'New bug bounty',
    new_tech_job_posting: 'New Job Posting',
    bug_bounty: 'Bug Bounty',
    jobs_board: 'Jobs',
  },
  am: {
    jobs_board: 'Jobs board',
    discussion: 'Discussions',
    tech_events: 'Tech Events-am',
    emoji_flag: flags.hy,
    name: 'Armenian',
    settings: 'կարգավորումները',
    push_notification: 'Push Notifications-hy',
    language: 'լեզու',
    up: 'up-am',
    down: 'down-am',
    search: 'Search-am...',
    be_kind_in_what_you_say: 'Be kind and respectful in what you say-am',
    new_post_title: 'New Discussion-am',
    bug_bounty: 'Bug Bounty-AM',
    jobs_board: 'Jobs-am',
    silicondzor: 'Silicondzor-AM',
  },
  ru: {
    jobs_board: 'Jobs board',
    discussion: 'Discussions',
    tech_events: 'Tech Events-ru',
    emoji_flag: flags.ru,
    name: 'Russian',
    settings: 'настройки',
    push_notification: 'Push Notifications-Ru',
    language: 'язык',
    up: 'up-ru',
    down: 'down-ru',
    search: 'Search-ru...',
    be_kind_in_what_you_say: 'Be kind and respectful in what you say-ru',
    new_post_title: 'New Discussion-ru',
    bug_bounty: 'Bug Bounty-Ru',
    jobs_board: 'Jobs-ru',
    silicondzor: 'Silicondzor-RU',
  },
};
